// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.proto

package com.guosen.zebra.core.message.json;

public final class JSONProto {
  private JSONProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_json_JsonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_json_JsonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_json_JsonReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_json_JsonReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\njson.proto\022\004json\"/\n\013JsonRequest\022\017\n\007mes" +
      "sage\030\001 \001(\t\022\017\n\007reqType\030\002 \001(\t\"\034\n\tJsonReply" +
      "\022\017\n\007message\030\001 \001(\tB7\n\"com.guosen.zebra.co" +
      "re.message.jsonB\tJSONProtoP\001\242\002\003HLWb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_json_JsonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_json_JsonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_json_JsonRequest_descriptor,
        new java.lang.String[] { "Message", "ReqType", });
    internal_static_json_JsonReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_json_JsonReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_json_JsonReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
