// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.proto

package com.guosen.zebra.core.message.json;

public interface JsonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:json.JsonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional string reqType = 2;</code>
   */
  java.lang.String getReqType();
  /**
   * <code>optional string reqType = 2;</code>
   */
  com.google.protobuf.ByteString
      getReqTypeBytes();
}
