// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.proto

package com.guosen.zebra.core.message.json;

public interface JsonReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:json.JsonReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
