// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example/health.proto

package com.guosen.zebra.core.monitor.health;

public final class ServiceParam {
  private ServiceParam() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.guosen.zebra.core.monitor.health.ServingStatus}
   */
  public enum ServingStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>SERVING = 1;</code>
     */
    SERVING(1),
    /**
     * <code>NOT_SERVING = 2;</code>
     */
    NOT_SERVING(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>SERVING = 1;</code>
     */
    public static final int SERVING_VALUE = 1;
    /**
     * <code>NOT_SERVING = 2;</code>
     */
    public static final int NOT_SERVING_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ServingStatus valueOf(int value) {
      return forNumber(value);
    }

    public static ServingStatus forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return SERVING;
        case 2: return NOT_SERVING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServingStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ServingStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServingStatus>() {
            public ServingStatus findValueByNumber(int number) {
              return ServingStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.guosen.zebra.core.monitor.health.ServiceParam.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServingStatus[] VALUES = values();

    public static ServingStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ServingStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.guosen.zebra.core.monitor.health.ServingStatus)
  }

  public interface HealthRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.guosen.zebra.core.monitor.health.HealthRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string service = 1;</code>
     */
    java.lang.String getService();
    /**
     * <code>optional string service = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceBytes();
  }
  /**
   * Protobuf type {@code com.guosen.zebra.core.monitor.health.HealthRequest}
   */
  public  static final class HealthRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.guosen.zebra.core.monitor.health.HealthRequest)
      HealthRequestOrBuilder {
    // Use HealthRequest.newBuilder() to construct.
    private HealthRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthRequest() {
      service_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HealthRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      @SuppressWarnings("unused")
	int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              service_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_HealthRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_HealthRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest.class, com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest.Builder.class);
    }

    public static final int SERVICE_FIELD_NUMBER = 1;
    private volatile java.lang.Object service_;
    /**
     * <code>optional string service = 1;</code>
     */
    public java.lang.String getService() {
      java.lang.Object ref = service_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        service_ = s;
        return s;
      }
    }
    /**
     * <code>optional string service = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      java.lang.Object ref = service_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServiceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, service_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServiceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, service_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest)) {
        return super.equals(obj);
      }
      com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest other = (com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest) obj;

      boolean result = true;
      result = result && getService()
          .equals(other.getService());
      return result;
    }

    @SuppressWarnings("unchecked")
	@java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SERVICE_FIELD_NUMBER;
      hash = (53 * hash) + getService().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.guosen.zebra.core.monitor.health.HealthRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.guosen.zebra.core.monitor.health.HealthRequest)
        com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_HealthRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_HealthRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest.class, com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest.Builder.class);
      }

      // Construct using com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        service_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_HealthRequest_descriptor;
      }

      public com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest getDefaultInstanceForType() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest.getDefaultInstance();
      }

      public com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest build() {
        com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest buildPartial() {
        com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest result = new com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest(this);
        result.service_ = service_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest) {
          return mergeFrom((com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest other) {
        if (other == com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest.getDefaultInstance()) return this;
        if (!other.getService().isEmpty()) {
          service_ = other.service_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object service_ = "";
      /**
       * <code>optional string service = 1;</code>
       */
      public java.lang.String getService() {
        java.lang.Object ref = service_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          service_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string service = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceBytes() {
        java.lang.Object ref = service_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          service_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string service = 1;</code>
       */
      public Builder setService(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        service_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string service = 1;</code>
       */
      public Builder clearService() {
        
        service_ = getDefaultInstance().getService();
        onChanged();
        return this;
      }
      /**
       * <code>optional string service = 1;</code>
       */
      public Builder setServiceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        service_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.guosen.zebra.core.monitor.health.HealthRequest)
    }

    // @@protoc_insertion_point(class_scope:com.guosen.zebra.core.monitor.health.HealthRequest)
    private static final com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest();
    }

    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthRequest>
        PARSER = new com.google.protobuf.AbstractParser<HealthRequest>() {
      public HealthRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HealthRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HealthRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthRequest> getParserForType() {
      return PARSER;
    }

    public com.guosen.zebra.core.monitor.health.ServiceParam.HealthRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HealthResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.guosen.zebra.core.monitor.health.HealthResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.guosen.zebra.core.monitor.health.ServingStatus status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>optional .com.guosen.zebra.core.monitor.health.ServingStatus status = 1;</code>
     */
    com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus getStatus();

    /**
     * <code>repeated string methodName = 2;</code>
     */
    java.util.List<java.lang.String>
        getMethodNameList();
    /**
     * <code>repeated string methodName = 2;</code>
     */
    int getMethodNameCount();
    /**
     * <code>repeated string methodName = 2;</code>
     */
    java.lang.String getMethodName(int index);
    /**
     * <code>repeated string methodName = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes(int index);

    /**
     * <code>optional string metrics = 3;</code>
     */
    java.lang.String getMetrics();
    /**
     * <code>optional string metrics = 3;</code>
     */
    com.google.protobuf.ByteString
        getMetricsBytes();
  }
  /**
   * Protobuf type {@code com.guosen.zebra.core.monitor.health.HealthResponse}
   */
  public  static final class HealthResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.guosen.zebra.core.monitor.health.HealthResponse)
      HealthResponseOrBuilder {
    // Use HealthResponse.newBuilder() to construct.
    private HealthResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthResponse() {
      status_ = 0;
      methodName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      metrics_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HealthResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                methodName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              methodName_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              metrics_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          methodName_ = methodName_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_HealthResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_HealthResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse.class, com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse.Builder.class);
    }

    @SuppressWarnings("unused")
	private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>optional .com.guosen.zebra.core.monitor.health.ServingStatus status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .com.guosen.zebra.core.monitor.health.ServingStatus status = 1;</code>
     */
    public com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus getStatus() {
      com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus result = com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus.valueOf(status_);
      return result == null ? com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus.UNRECOGNIZED : result;
    }

    public static final int METHODNAME_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList methodName_;
    /**
     * <code>repeated string methodName = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMethodNameList() {
      return methodName_;
    }
    /**
     * <code>repeated string methodName = 2;</code>
     */
    public int getMethodNameCount() {
      return methodName_.size();
    }
    /**
     * <code>repeated string methodName = 2;</code>
     */
    public java.lang.String getMethodName(int index) {
      return methodName_.get(index);
    }
    /**
     * <code>repeated string methodName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes(int index) {
      return methodName_.getByteString(index);
    }

    public static final int METRICS_FIELD_NUMBER = 3;
    private volatile java.lang.Object metrics_;
    /**
     * <code>optional string metrics = 3;</code>
     */
    public java.lang.String getMetrics() {
      java.lang.Object ref = metrics_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metrics_ = s;
        return s;
      }
    }
    /**
     * <code>optional string metrics = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMetricsBytes() {
      java.lang.Object ref = metrics_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metrics_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus.UNKNOWN.getNumber()) {
        output.writeEnum(1, status_);
      }
      for (int i = 0; i < methodName_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_.getRaw(i));
      }
      if (!getMetricsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, metrics_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < methodName_.size(); i++) {
          dataSize += computeStringSizeNoTag(methodName_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMethodNameList().size();
      }
      if (!getMetricsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, metrics_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse)) {
        return super.equals(obj);
      }
      com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse other = (com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse) obj;

      boolean result = true;
      result = result && status_ == other.status_;
      result = result && getMethodNameList()
          .equals(other.getMethodNameList());
      result = result && getMetrics()
          .equals(other.getMetrics());
      return result;
    }

    @SuppressWarnings("unchecked")
	@java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      if (getMethodNameCount() > 0) {
        hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
        hash = (53 * hash) + getMethodNameList().hashCode();
      }
      hash = (37 * hash) + METRICS_FIELD_NUMBER;
      hash = (53 * hash) + getMetrics().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.guosen.zebra.core.monitor.health.HealthResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.guosen.zebra.core.monitor.health.HealthResponse)
        com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_HealthResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_HealthResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse.class, com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse.Builder.class);
      }

      // Construct using com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        methodName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        metrics_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_HealthResponse_descriptor;
      }

      public com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse getDefaultInstanceForType() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse.getDefaultInstance();
      }

      public com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse build() {
        com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @SuppressWarnings("unused")
	public com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse buildPartial() {
        com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse result = new com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.status_ = status_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          methodName_ = methodName_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.methodName_ = methodName_;
        result.metrics_ = metrics_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse) {
          return mergeFrom((com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse other) {
        if (other == com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.methodName_.isEmpty()) {
          if (methodName_.isEmpty()) {
            methodName_ = other.methodName_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMethodNameIsMutable();
            methodName_.addAll(other.methodName_);
          }
          onChanged();
        }
        if (!other.getMetrics().isEmpty()) {
          metrics_ = other.metrics_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>optional .com.guosen.zebra.core.monitor.health.ServingStatus status = 1;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>optional .com.guosen.zebra.core.monitor.health.ServingStatus status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.guosen.zebra.core.monitor.health.ServingStatus status = 1;</code>
       */
      public com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus getStatus() {
        com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus result = com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus.valueOf(status_);
        return result == null ? com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.guosen.zebra.core.monitor.health.ServingStatus status = 1;</code>
       */
      public Builder setStatus(com.guosen.zebra.core.monitor.health.ServiceParam.ServingStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.guosen.zebra.core.monitor.health.ServingStatus status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList methodName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMethodNameIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          methodName_ = new com.google.protobuf.LazyStringArrayList(methodName_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string methodName = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMethodNameList() {
        return methodName_.getUnmodifiableView();
      }
      /**
       * <code>repeated string methodName = 2;</code>
       */
      public int getMethodNameCount() {
        return methodName_.size();
      }
      /**
       * <code>repeated string methodName = 2;</code>
       */
      public java.lang.String getMethodName(int index) {
        return methodName_.get(index);
      }
      /**
       * <code>repeated string methodName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes(int index) {
        return methodName_.getByteString(index);
      }
      /**
       * <code>repeated string methodName = 2;</code>
       */
      public Builder setMethodName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMethodNameIsMutable();
        methodName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodName = 2;</code>
       */
      public Builder addMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMethodNameIsMutable();
        methodName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodName = 2;</code>
       */
      public Builder addAllMethodName(
          java.lang.Iterable<java.lang.String> values) {
        ensureMethodNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, methodName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodName = 2;</code>
       */
      public Builder clearMethodName() {
        methodName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodName = 2;</code>
       */
      public Builder addMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMethodNameIsMutable();
        methodName_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object metrics_ = "";
      /**
       * <code>optional string metrics = 3;</code>
       */
      public java.lang.String getMetrics() {
        java.lang.Object ref = metrics_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          metrics_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string metrics = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMetricsBytes() {
        java.lang.Object ref = metrics_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metrics_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string metrics = 3;</code>
       */
      public Builder setMetrics(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        metrics_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string metrics = 3;</code>
       */
      public Builder clearMetrics() {
        
        metrics_ = getDefaultInstance().getMetrics();
        onChanged();
        return this;
      }
      /**
       * <code>optional string metrics = 3;</code>
       */
      public Builder setMetricsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        metrics_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.guosen.zebra.core.monitor.health.HealthResponse)
    }

    // @@protoc_insertion_point(class_scope:com.guosen.zebra.core.monitor.health.HealthResponse)
    private static final com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse();
    }

    public static com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthResponse>
        PARSER = new com.google.protobuf.AbstractParser<HealthResponse>() {
      public HealthResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HealthResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HealthResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthResponse> getParserForType() {
      return PARSER;
    }

    public com.guosen.zebra.core.monitor.health.ServiceParam.HealthResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SentinelRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.guosen.zebra.core.monitor.health.SentinelRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string data = 1;</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>optional string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code com.guosen.zebra.core.monitor.health.SentinelRequest}
   */
  public  static final class SentinelRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.guosen.zebra.core.monitor.health.SentinelRequest)
      SentinelRequestOrBuilder {
    // Use SentinelRequest.newBuilder() to construct.
    private SentinelRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SentinelRequest() {
      data_ = "";
      type_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SentinelRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      @SuppressWarnings("unused")
	int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_SentinelRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_SentinelRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest.class, com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private volatile java.lang.Object data_;
    /**
     * <code>optional string data = 1;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>optional string data = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>optional string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>optional string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, data_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, data_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest)) {
        return super.equals(obj);
      }
      com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest other = (com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest) obj;

      boolean result = true;
      result = result && getData()
          .equals(other.getData());
      result = result && getType()
          .equals(other.getType());
      return result;
    }

    @SuppressWarnings("unchecked")
	@java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.guosen.zebra.core.monitor.health.SentinelRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.guosen.zebra.core.monitor.health.SentinelRequest)
        com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_SentinelRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_SentinelRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest.class, com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest.Builder.class);
      }

      // Construct using com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        data_ = "";

        type_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_SentinelRequest_descriptor;
      }

      public com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest getDefaultInstanceForType() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest.getDefaultInstance();
      }

      public com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest build() {
        com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest buildPartial() {
        com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest result = new com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest(this);
        result.data_ = data_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest) {
          return mergeFrom((com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest other) {
        if (other == com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest.getDefaultInstance()) return this;
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 1;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 1;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 1;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 1;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.guosen.zebra.core.monitor.health.SentinelRequest)
    }

    // @@protoc_insertion_point(class_scope:com.guosen.zebra.core.monitor.health.SentinelRequest)
    private static final com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest();
    }

    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SentinelRequest>
        PARSER = new com.google.protobuf.AbstractParser<SentinelRequest>() {
      public SentinelRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SentinelRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SentinelRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SentinelRequest> getParserForType() {
      return PARSER;
    }

    public com.guosen.zebra.core.monitor.health.ServiceParam.SentinelRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SentinelResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.guosen.zebra.core.monitor.health.SentinelResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>optional string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code com.guosen.zebra.core.monitor.health.SentinelResponse}
   */
  public  static final class SentinelResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.guosen.zebra.core.monitor.health.SentinelResponse)
      SentinelResponseOrBuilder {
    // Use SentinelResponse.newBuilder() to construct.
    private SentinelResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SentinelResponse() {
      code_ = 0;
      msg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    @SuppressWarnings("unused")
	private SentinelResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_SentinelResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_SentinelResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse.class, com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>optional int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse)) {
        return super.equals(obj);
      }
      com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse other = (com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse) obj;

      boolean result = true;
      result = result && (getCode()
          == other.getCode());
      result = result && getMsg()
          .equals(other.getMsg());
      return result;
    }

    @SuppressWarnings("unchecked")
	@java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.guosen.zebra.core.monitor.health.SentinelResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.guosen.zebra.core.monitor.health.SentinelResponse)
        com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_SentinelResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_SentinelResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse.class, com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse.Builder.class);
      }

      // Construct using com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 0;

        msg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.internal_static_com_guosen_zebra_core_monitor_health_SentinelResponse_descriptor;
      }

      public com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse getDefaultInstanceForType() {
        return com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse.getDefaultInstance();
      }

      public com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse build() {
        com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse buildPartial() {
        com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse result = new com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse(this);
        result.code_ = code_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse) {
          return mergeFrom((com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse other) {
        if (other == com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>optional int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.guosen.zebra.core.monitor.health.SentinelResponse)
    }

    // @@protoc_insertion_point(class_scope:com.guosen.zebra.core.monitor.health.SentinelResponse)
    private static final com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse();
    }

    public static com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SentinelResponse>
        PARSER = new com.google.protobuf.AbstractParser<SentinelResponse>() {
      public SentinelResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SentinelResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SentinelResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SentinelResponse> getParserForType() {
      return PARSER;
    }

    public com.guosen.zebra.core.monitor.health.ServiceParam.SentinelResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_guosen_zebra_core_monitor_health_HealthRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_guosen_zebra_core_monitor_health_HealthRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_guosen_zebra_core_monitor_health_HealthResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_guosen_zebra_core_monitor_health_HealthResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_guosen_zebra_core_monitor_health_SentinelRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_guosen_zebra_core_monitor_health_SentinelRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_guosen_zebra_core_monitor_health_SentinelResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_guosen_zebra_core_monitor_health_SentinelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024example/health.proto\022$com.guosen.zebra" +
      ".core.monitor.health\" \n\rHealthRequest\022\017\n" +
      "\007service\030\001 \001(\t\"z\n\016HealthResponse\022C\n\006stat" +
      "us\030\001 \001(\01623.com.guosen.zebra.core.monitor" +
      ".health.ServingStatus\022\022\n\nmethodName\030\002 \003(" +
      "\t\022\017\n\007metrics\030\003 \001(\t\"-\n\017SentinelRequest\022\014\n" +
      "\004data\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\"-\n\020SentinelRes" +
      "ponse\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t*:\n\rServ" +
      "ingStatus\022\013\n\007UNKNOWN\020\000\022\013\n\007SERVING\020\001\022\017\n\013N" +
      "OT_SERVING\020\0022\354\003\n\006Health\022r\n\005Check\0223.com.g",
      "uosen.zebra.core.monitor.health.HealthRe" +
      "quest\0324.com.guosen.zebra.core.monitor.he" +
      "alth.HealthResponse\022w\n\ngetMethods\0223.com." +
      "guosen.zebra.core.monitor.health.HealthR" +
      "equest\0324.com.guosen.zebra.core.monitor.h" +
      "ealth.HealthResponse\022w\n\ngetMetrics\0223.com" +
      ".guosen.zebra.core.monitor.health.Health" +
      "Request\0324.com.guosen.zebra.core.monitor." +
      "health.HealthResponse\022|\n\013setSentinel\0225.c" +
      "om.guosen.zebra.core.monitor.health.Sent",
      "inelRequest\0326.com.guosen.zebra.core.moni" +
      "tor.health.SentinelResponseB4\n$com.guose" +
      "n.zebra.core.monitor.healthB\014ServicePara" +
      "mb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_guosen_zebra_core_monitor_health_HealthRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_guosen_zebra_core_monitor_health_HealthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_guosen_zebra_core_monitor_health_HealthRequest_descriptor,
        new java.lang.String[] { "Service", });
    internal_static_com_guosen_zebra_core_monitor_health_HealthResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_guosen_zebra_core_monitor_health_HealthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_guosen_zebra_core_monitor_health_HealthResponse_descriptor,
        new java.lang.String[] { "Status", "MethodName", "Metrics", });
    internal_static_com_guosen_zebra_core_monitor_health_SentinelRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_guosen_zebra_core_monitor_health_SentinelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_guosen_zebra_core_monitor_health_SentinelRequest_descriptor,
        new java.lang.String[] { "Data", "Type", });
    internal_static_com_guosen_zebra_core_monitor_health_SentinelResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_guosen_zebra_core_monitor_health_SentinelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_guosen_zebra_core_monitor_health_SentinelResponse_descriptor,
        new java.lang.String[] { "Code", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
